CUPDLP_HOME = ENV["CUPDLP_HOME"]
LIBCUPDLP_PATH = joinpath(CUPDLP_HOME, "build/lib/")
println("Detect CUPDLP_HOME at $(CUPDLP_HOME)")

if Sys.islinux()
    LIBSUFFIX = ".so"
elseif Sys.iswindows()
    LIBSUFFIX = ".dll"
else
    LIBSUFFIX = ".dylib"
end

# LIBJLCUPDLP_PATH is the absolute path of libjlcupdlp

@enum INT_PARAM N_ITER_LIM = 1 IF_SCALING I_SCALING_METHOD E_LINE_SEARCH_METHOD E_RESTART_METHOD IF_RUIZ_SCALING IF_L2_SCALING IF_PC_SCALING N_LOG_INTERVAL IF_PRESOLVE N_INT_USER_PARAM

@enum FLOAT_PARAM D_SCALING_LIMIT = 1 D_PRIMAL_TOL D_DUAL_TOL D_GAP_TOL D_FEAS_TOL D_TIME_LIM N_FLOAT_USER_PARAM